container_config: &container_config
  docker:
    - image: strebitz/docker-ci:17.06-2-g7106469
  environment:
    - DOCKER_IMAGE_NAME: strebitz/terraform

version: 2
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run: make workspace/docker-image.tar.gz
      - persist_to_workspace:
          root: workspace
          paths:
            - docker-image.tar.gz
      - store_artifacts:
          path: workspace/docker-image.tar.gz
  deploy:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - setup_remote_docker
      - run: gzip -c -d workspace/docker-image.tar.gz | docker load
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run: docker tag ${DOCKER_IMAGE_NAME} ${DOCKER_IMAGE_NAME}:$(git describe)
      - run:
          command: |
            for image_tag in ${DOCKER_IMAGE_NAME}:$(git describe) ${DOCKER_IMAGE_NAME}
            do
              docker push ${image_tag}
            done

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: /^master$/
          requires:
            - build
