container_config: &container_config
  docker:
    - image: docker:17.06.0-ce-git
  working_directory: /tmp

version: 2
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir -p workspace
      - run: docker build -t strebitz/terraform .
      - run: docker save strebitz/terraform | gzip -c > workspace/docker-image_strebitz-terraform.tar.gz
      - persist_to_workspace:
          root: workspace
          paths:
            - docker-image_strebitz-terraform.tar.gz
      - store_artifacts:
          path: workspace/docker-image_strebitz-terraform.tar.gz
  deploy:
    <<: *container_config
    steps:
      - attach_workspace:
          at: workspace
      - setup_remote_docker
      - run: gzip -c -d workspace/strebitz-terraform.tar.gz | docker load
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker tag strebitz/terraform strebitz/terraform:$(git describe)
      - run: docker push strebitz/terraform strebitz/terraform:$(git describe)

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: /^master$/
          requires:
            - build
