container_config: &container_config
  docker:
    - image: docker:17.06.0-ce

version: 2
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t strebitz/terraform:latest .
  deploy:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag strebitz/terraform:latest strebitz/terraform:$CIRCLE_TAG
          docker push strebitz/terraform:latest strebitz/terraform:$CIRCLE_TAG

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: /^master$/
          requires:
            - build
