container_config: &container_config
  docker:
    - image: docker:17.06.0-ce-git

version: 2
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t strebitz/terraform .
  deploy:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker tag strebitz/terraform:latest strebitz/terraform:$(git describe)
      - run: docker push strebitz/terraform:latest strebitz/terraform:$(git describe)

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: /^master$/
          requires:
            - build
