container_config: &container_config
  docker:
    - image: docker:17.06.0-ce-git

version: 2
jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            mkdir -p workspace
            docker build -t strebitz/terraform .
            docker save strebitz/terraform | gzip -c > workspace/docker-image_strebitz-terraform.tar.gz
      - persist_to_workspace:
          root: workspace
          paths:
            - docker-image_strebitz-terraform.tar.gz
      - store_artifacts:
          path: workspace/docker-image_strebitz-terraform.tar.gz
  deploy:
    <<: *container_config
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - setup_remote_docker
      - run:
          command: |
            gzip -c -d workspace/docker-image_strebitz-terraform.tar.gz | docker load
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag strebitz/terraform strebitz/terraform:$(git describe)
            for image_tag in strebitz/terraform strebitz/terraform:$(git describe); do docker push ${image_tag}; done

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: /^master$/
          requires:
            - build
